/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Libro;

/**
 *
 * @author patri
 */
public class FrmLibro extends javax.swing.JFrame {
    Libro libro = new Libro();
    /**
     * Creates new form frmLibro
     */
    public FrmLibro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDisponible = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        rdoSi = new javax.swing.JRadioButton();
        rdoNo = new javax.swing.JRadioButton();
        chkDisponible = new javax.swing.JCheckBox();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingreso de Libros");

        lblTitulo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 255));
        lblTitulo.setText("Ingreso de Libros");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Titulo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Autor");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Publicación");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Precio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Disponible");

        grupoDisponible.add(rdoSi);
        rdoSi.setText("Si");

        grupoDisponible.add(rdoNo);
        rdoNo.setText("No");

        chkDisponible.setText("Disponible");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idLibro", "Titulo", "Autor", "Publicación", "Precio", "Disponible"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        grilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grillaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(lblTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLimpiar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTitulo)
                                            .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdoSi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rdoNo))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnGuardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnListar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnModificar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminar)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkDisponible)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEliminar, btnGuardar, btnLimpiar, btnListar, btnModificar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdoSi)
                    .addComponent(rdoNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGuardar)
                    .addComponent(btnListar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtTitulo.setText("");
        txtAutor.setText("");
        txtDia.setText("");
        txtMes.setText("");
        txtAnio.setText("");
        txtPrecio.setText("");
        
        //rdoNo.setSelected(true);        
        // para limpiar todos los radios o rdo
        grupoDisponible.clearSelection();  
        libro.limpiar();
        txtTitulo.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // validar
        if(txtTitulo.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Titulo del libro");
            txtTitulo.requestFocus();
        }
        else if(txtAutor.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Autor del libro");
            txtAutor.requestFocus();
        }
        else if(txtDia.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Día de la publicación");
            txtDia.requestFocus();
        }
        else if(txtMes.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Mes de la publicación");
            txtMes.requestFocus();
        }
        else if(txtAnio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Año de la publicación");
            txtAnio.requestFocus();
        }
        else if(txtPrecio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el precio del libro");    
            txtPrecio.requestFocus();
        }
        else if(!rdoSi.isSelected() && !rdoNo.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Debe especificar si esta disponible el libro");
        }
        else
        {
            // traspasar los datos del formulario (txt,rdo, etc.)
            // al objeto libro
            libro.setIdLibro(0);
            libro.setTitulo(txtTitulo.getText().trim().toUpperCase());
            libro.setAutor(txtAutor.getText().trim().toUpperCase());
            
            //formatear una fecha
            Date fecha;
            SimpleDateFormat formatoFecha = new SimpleDateFormat("mm/dd/yyyy");
            
            String f = txtMes.getText() + "/" + txtDia.getText() + "/" + txtAnio.getText();
            
            try {
                fecha = formatoFecha.parse(f);
                libro.setPublicacion(fecha);
            } catch (ParseException ex) {
                Logger.getLogger(FrmLibro.class.getName()).log(Level.SEVERE, null, ex);
            }
            // convertir precio a un numero
            int precio = Integer.parseInt(txtPrecio.getText());
            libro.setPrecio(precio);
            
            libro.setDisponible(rdoSi.isSelected());
            
            //JOptionPane.showMessageDialog(this, libro);
            Registro registro = new Registro();
            Boolean res = registro.agregar(libro);
            
            if(res)
            {
                JOptionPane.showMessageDialog(this, "Datos guardados");
                btnLimpiar.doClick(); // simula un clic al botón
            }
            else
                JOptionPane.showMessageDialog(this, "Datos NO guardados");
                
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) grilla.getModel();
        modelo.setRowCount(0);
        
        // invocar el metodo buscarTodos
        Registro registro = new Registro();
        List<Libro> lista = registro.buscarTodos();
        
        for(Libro aux: lista)
        {
            modelo.addRow(new Object[]{
                aux.getIdLibro(),
                aux.getTitulo(),
                aux.getAutor(),
                aux.getPublicacion(),
                aux.getPrecio(),
                aux.isDisponible()
            });
            
        }
       
        
        
    }//GEN-LAST:event_btnListarActionPerformed

    private void grillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grillaMouseClicked
        // TODO add your handling code here:
        int row = grilla.rowAtPoint(evt.getPoint());
        
        // obtiene el id como string y ser convierte en un numero (int) y es entregado al obj libro
        int id = Integer.parseInt(grilla.getValueAt(row, 0).toString());
        libro.setIdLibro(id);
        
        txtTitulo.setText(grilla.getValueAt(row, 1).toString() );
        txtAutor.setText(grilla.getValueAt(row, 2).toString() );
        
        //  System.out.println("" + grilla.getValueAt(row, 3).toString() );
        
        String fecha = grilla.getValueAt(row, 3).toString();
        txtDia.setText(fecha.substring(8));
        txtMes.setText(fecha.substring(5,7));
        txtAnio.setText(fecha.substring(0,4));
        
        txtPrecio.setText(grilla.getValueAt(row, 4).toString());
        
        if(grilla.getValueAt(row, 5).toString().equals("true"))
            rdoSi.setSelected(true);
        else
            rdoNo.setSelected(true);
        
        // completar el formulario con el resto de los datos de la fila 
        // clickeada por el usuario. (parse... substring)
        
    }//GEN-LAST:event_grillaMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if(libro.getIdLibro() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un libro para modificar");
            txtTitulo.requestFocus();
        }
        else if(txtTitulo.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Titulo del libro");
            txtTitulo.requestFocus();
        }
        else if(txtAutor.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Autor del libro");
            txtAutor.requestFocus();
        }
        else if(txtDia.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Día de la publicación");
            txtDia.requestFocus();
        }
        else if(txtMes.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Mes de la publicación");
            txtMes.requestFocus();
        }
        else if(txtAnio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el Año de la publicación");
            txtAnio.requestFocus();
        }
        else if(txtPrecio.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe especificar el precio del libro");    
            txtPrecio.requestFocus();
        }
        else if(!rdoSi.isSelected() && !rdoNo.isSelected())
        {
            JOptionPane.showMessageDialog(this, "Debe especificar si esta disponible el libro");
        }
        else
        {
            // traspasar los datos del formulario (txt,rdo, etc.)
            // al objeto libro
            // libro.setIdLibro(0); Eliminar porque si vale cero no modificará la fila en la BDD
            libro.setTitulo(txtTitulo.getText().trim().toUpperCase());
            libro.setAutor(txtAutor.getText().trim().toUpperCase());
            
            //formatear una fecha
            Date fecha;
            SimpleDateFormat formatoFecha = new SimpleDateFormat("mm/dd/yyyy");
            // 
            String f = txtMes.getText() + "/" + txtDia.getText() + "/" + txtAnio.getText();
            
            try {
                fecha = formatoFecha.parse(f);
                libro.setPublicacion(fecha);
            } catch (ParseException ex) {
                Logger.getLogger(FrmLibro.class.getName()).log(Level.SEVERE, null, ex);
            }
            // convertir precio a un numero
            int precio = Integer.parseInt(txtPrecio.getText());
            libro.setPrecio(precio);
            
            libro.setDisponible(rdoSi.isSelected());
            
            //JOptionPane.showMessageDialog(this, libro);
            Registro registro = new Registro();
            Boolean res = registro.actualizar(libro); // invocar el actualizar
            
            if(res)
            {
                JOptionPane.showMessageDialog(this, "Datos guardados");
                btnLimpiar.doClick(); // simula un clic al botón
            }
            else
                JOptionPane.showMessageDialog(this, "Datos NO guardados");
        }     
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(libro.getIdLibro() == 0)
        {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un libro para modificar");
            txtTitulo.requestFocus();
        }
        else
        {
            Registro registro = new Registro();
            Boolean res = registro.eliminar(libro.getIdLibro()); // invocar el eliminar y entregar el ID del libro

            if(res)
            {
                JOptionPane.showMessageDialog(this, "El libro fue eliminado");
                btnLimpiar.doClick(); // simula un clic al botón
            }
            else
                JOptionPane.showMessageDialog(this, "El libro No fue eliminado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JCheckBox chkDisponible;
    private javax.swing.JTable grilla;
    private javax.swing.ButtonGroup grupoDisponible;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdoNo;
    private javax.swing.JRadioButton rdoSi;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
